version: "3"
services:
    client:
        build:
          context: ./client
        restart: always
        ports:
            - "3000:3000"
        volumes:
            - ./client:/client
        links:
            - api
        networks:
            - webappnetwork
    api:
        build:
          context: ./server
        restart: always
        ports:
            - "4000:4000"
        volumes:
            - ./server:/server
        networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge